version: 2.1

jobs:
  development:
    docker:
      - image: 'cimg/node:17.9.0'
    steps:
      - checkout
      - run:
          name: check directory
          command: ls -la ; 
      - run:
          name: Docker check
          command: sudo apt-get update
                   sudo apt-get install 
                   ca-certificates 
                   curl 
                   gnupg 
                   lsb-release
                   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/       docker-archive-keyring.gpg
                   echo 
                   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu 
                   $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                   sudo apt-get update
                   sudo apt-get install docker-ce docker-ce-cli containerd.io
                   apt-cache madison docker-ce
                   sudo docker ps -a
      - add_ssh_keys:
          fingerprints:
            - "86:d5:09:4a:54:79:25:43:4f:94:59:42:fe:82:2b:04"
      - run:
          name: deploy
          command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $VM_USERNAME@$VM_PUB_IP 
                   "cd backend_eduvalor ; ls -la ; "

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - development:
          filters:
            branches:
              only: develop
