version: 2.1

jobs:
  development:
    docker:
      - image: 'cimg/node:17.9.0'
    steps:
      - checkout
      - run:
          name: check directory
          command: ls -la ; 
      - run:
          name: check software update
          command: sudo apt-get update -y ;
      - add_ssh_keys:
          fingerprints:
            - "d9:40:2f:a7:21:4a:32:eb:25:52:77:f5:31:b9:66:05"
      - run:
          name: deploy
          command: ssh -o StrictHostKeyChecking=no $VM_USERNAME@$VM_PUB_IP 
                   "cd backend_eduvalor ;
                   ls -l ;
                   git checkout develop ;
                   git branch ;
                   git pull origin develop ;
                   rm -rf .env ;
                   touch .env ;
                   echo 'DATABASE_URL=$DATABASE_URL' >> .env ;
                   echo 'ENDPOINT=$ENDPOINT' >> .env ;
                   echo 'MINIO_PORT=$MINIO_PORT' >> .env ;
                   echo 'MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY' >> .env ;
                   echo 'MINIO_SECRET_KEY=$MINIO_SECRET_KEY' >> .env ; 
                   chmod +x ./deploy_dev.sh ;
                   ./deploy_dev.sh"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - development:
          filters:
            branches:
              only: develop
