version: 2.1

jobs:
  development:
    docker:
      - image: 'cimg/node:17.9.0'
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e6:66:8c:66:aa:1d:f6:5b:24:a1:8f:88:6d:be:17:ff"
      - run:
          name: deploy
          command: ssh -o PasswordAuthentication=no $VM_USERNAME@$VM_PUB_IP
                   "cd backend_eduvalor
                   ls -la
                   git branch -a"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - development:
          filters:
            branches:
              only: develop
