version: 2.1

jobs:
  development:
    docker:
      - image: 'cimg/node:17.9.0'
    steps:
      - checkout
      - run:
          name: test
          command: echo "Hello World"
      - add_ssh_keys:
          fingerprints:
            - "5d:79:44:30:7c:67:3e:be:f7:b3:be:dd:ef:bc:f3:b1"
      - run:
          name: deploy
          command: ssh -o StrictHostKeyChecking=no $VM_USERNAME@$VM_PUB_IP

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - development:
          filters:
            branches:
              only: develop
