version: 2.1

jobs:
  deployment:
    docker:
      - image: 'cimg/node:17.9.0'
    steps:
      - checkout
      - run: node --version
      - run:
          name: test
          command: echo "Hello NestJS from dev"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - development:
          filters:
            branches:
              only: develop
